### ISSUE TITLE
Missing dropdown 

### ISSUE THREAD

**Issue by diego898** [randy3k/LaTeXZeta#2]
Im not seeing the `\` dropdown box? And the `a, etc shortcuts arent working? I have latextools installed

**Comment by randy3k** [comment]
Did you install LaTeXZeta? Please try restarting Sublime Text if LaTeXZeta is freshly installed.

**Comment by diego898** [comment]
I did, and also restarted sublime

**Comment by randy3k** [comment]
Did you choose LaTeX syntax? Also note that `a is not available at math environment.

**Comment by diego898** [comment]
I did choose latex syntax. Can you please clarify what you mean by `a not avaiable in math? 

Also, trying to repeat the example in your documentation, 

![](https://media.giphy.com/media/l3q2Kj0YVQTkXQYbm/giphy.gif)

the dropdown doesnt fill in all available space?

**Comment by randy3k** [comment]
Oops, I meant "is only available in math env".

**Comment by diego898** [comment]
I did try it in the math enviroment

**Comment by randy3k** [comment]
What does "not filling the available spaces" mean?

**Comment by diego898** [comment]
Here, you can see that when I type `\long`, the entire dropdown just shows `\long...` on every line. Also, that im trying `a in math mode:

![](https://media.giphy.com/media/l0ExrPby6gxmWXlGU/giphy.gif)

**Comment by randy3k** [comment]
could it be caused by the theme that you are using? I don't experience such an issue.

**Comment by diego898** [comment]
I have removed my theme, using the default, restarted sublime and see the following:

![](https://media.giphy.com/media/l0Ex14XDMmzPFrQcM/giphy.gif)

**Comment by randy3k** [comment]
I just discovered that `\longxxxx` commands are not suggested by LaTeXZeta. Did you install other packages for latex?

**Comment by diego898** [comment]
I was trying to recreate this screen shot on your readme: 

![](https://cloud.githubusercontent.com/assets/1690993/20915374/743dfcd2-bb53-11e6-9e29-a1af80356405.png)

I also have the following 4 packages installed for latex:

- LatexTools 
- LatexZeta
- Latex-cwl
- LatexSmartQoutes

**Comment by randy3k** [comment]
Oh....it was a screen a while ago, a lot of things have changed since then, specifically, the `\longxxx` commands are not there anymore (though I think we should add them back).

**Comment by diego898** [comment]
Hmm ok Ill have to figure out who is doing the suggestion then. 

But also in that gif you can see that the `a isnt working in math mode?

**Comment by randy3k** [comment]
It might due to the loading order of the packages. I justed recognized that LaTeXTools is always installed at "Packages" folder while LaTeXZeta is installed at the "Installed Packages" folder. It may affect the loading order.

I have submitted a new version to Package Control, hopes that it will be upgraded soon.

**Comment by diego898** [comment]
Hello again - just wondering the status on this?

**Comment by randy3k** [comment]
Oh, I thought it was fixed..

**Comment by diego898** [comment]
Thanks @randy3k - it is indeed fixed
