### ISSUE TITLE
Cite/ref autocompletions stopped working with LaTeXZeta

### ISSUE THREAD

**Issue by denisjam** [randy3k/LaTeXZeta#4]
After updating LaTeXTools to the latest version, cite/ref dropdown menu stopped appearing. I tried looking into LaTeXTools, but then figured that the issue might be caused by LaTeXZeta. Dropdown menu appears if and only if I remove LaTeXZeta.

I am running LaTeXTools v3.13.3 on ST3.

**Comment by randy3k** [comment]
If you meant the automatic pop up, I would reproduce it. It would because LaTeXZeta provides a version of auto matching of `{}` which overwrites LaTeXTools defaults.

It will be fixed and meanwhile, you could use the keybind <kbd>C+l, x</kbd> to activate the menu.

**Comment by randy3k** [comment]
v0.0.11 should fix it.
